version: "3.8"
services:
  api:
    image: house-price-mlops:latest  # Si ya tienes una imagen, puedes usarla directamente
    build: # o se puede construir desde el Dockerfile
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # exposición en el host
    environment:
      API_PORT: 8000
      WANDB_API_KEY: ${WANDB_API_KEY}
      WANDB_ARTIFACT_PATH: ${WANDB_ARTIFACT_PATH}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 5s
      timeout: 3s
      retries: 5
  test:
    image: test-house-price-mlops 
    build:
      context: ./test
      dockerfile: Dockerfile  
    depends_on:
      api:
        condition: service_healthy
    environment:
      API_HOST: api
      API_PORT: 8000
  web:
    image: web-house-price-mlops    
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    depends_on:
      api:
        condition: service_healthy
    environment:
      WEB_APP_PORT: 8080
      API_HOST: api
      API_PORT: 8000