version: "3.8"

services:
  api:
    image: javierpg.azurecr.io/house-price-mlops:ci
    ports:
      - "8000:8000"
    environment:
      - API_PORT=8000
      - WANDB_API_KEY=${WANDB_API_KEY}
      - WANDB_ARTIFACT_PATH=${WANDB_ARTIFACT_PATH}
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
        interval: 5s
        timeout: 3s
        retries: 5
  web:
    image: javierpg.azurecr.io/web-house-price-mlops:ci
    ports:
      - "8080:8080"
    depends_on:
      api:
        condition: service_healthy
    environment:
      - WEB_APP_PORT=8080
      - API_HOST=api
      - API_PORT=8000