_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 15
                - 16
                - 23
                - 55
                - 62
            "4": 3.11.10
            "5": 0.19.7
            "8":
                - 1
                - 5
            "12": 0.19.7
            "13": linux-x86_64
        viz:
            learning_curve:
                historyFieldSettings:
                    key: learning_curve
                    x-axis: _step
                id: wandb/learning_curve/v1
            outlier_candidates:
                historyFieldSettings:
                    key: outlier_candidates
                    x-axis: _step
                id: wandb/outliers/v1
            residuals:
                historyFieldSettings:
                    key: residuals
                    x-axis: _step
                id: wandb/residuals_plot/v1
            summary_metrics:
                historyFieldSettings:
                    key: summary_metrics
                    x-axis: _step
                id: wandb/metrics/v1
num_estimators:
    value: 100
